# directories
INSTALL_DIRECTORY:=/usr/local
BOOST:=$(INSTALL_DIRECTORY)
CHOMP:=$(INSTALL_DIRECTORY)
SDSL:=$(INSTALL_DIRECTORY)
CLUSTERDELEGATOR:=$(INSTALL_DIRECTORY)
CIMG:=$(INSTALL_DIRECTORY)
DATABASE:=$(PREFIX)./
X11:=$(INSTALL_DIRECTORY)
include $(PREFIX)makefile.dep
PREREQ:=$(BOOST) $(CHOMP) $(SDSL) $(CLUSTERDELEGATOR) $(DATABASE) $(X11)
DIRECTORIES:=$(filter-out $(INSTALL_DIRECTORY), $(PREREQ))
OBJDIR := ./build
SRCDIR := ./source

# Set make variables CC, CXX, CXXFLAGS, LDFLAGS, LDLIBS
CC := mpicxx
CXX := mpicxx
CXXFLAGS := -std=c++11 -Wall -O3 -ggdb -ftemplate-depth-2048
CXXFLAGS += $(patsubst %,-I%/include,$(DIRECTORIES))
LDFLAGS += $(patsubst %,-L%/lib,$(DIRECTORIES))
#LDFLAGS += $(patsubst %,-L%/lib -Wl,-rpath,"$(abspath %)/lib",$(DIRECTORIES))
CXXFLAGS += -I$(MODELDIR)
LDLIBS := -lboost_serialization -lboost_thread -lboost_system -lboost_chrono
LDLIBS += -lX11 -lmpfr -lgmp
LDLIBS += -lsdsl -ldivsufsort -ldivsufsort64

# ADD OPTIONAL CAPD SUPPORT IF REQUESTED
ifeq ($(USE_CAPD),yes)
CXXFLAGS += `capd-config --cflags`
LDLIBS += `capd-config --libs`
endif
