# directories where prerequisites can be found
HOMEDIR := ..
CHOMP := ./
CLUSTER := $(HOMEDIR)/cluster-delegator
BOOST := /usr/local
SDSL := $(HOMEDIR)/sdsl
GRAPHICS := /opt/X11
MODELDIR := data/GenericMap  #user overrides this

# CAPD SUPPORT
CAPD :=
CAPDINCS :=
CAPDLIBS :=
ifeq ($(USE_CAPD),yes)
CAPD += ../capd/
#CAPDINCS += `../capd/bin/capd-config --cflags`
#CAPDLIBS += `../capd/bin/capd-config --libs`
CAPDINCS += `capd-config --cflags`
CAPDLIBS += `capd-config --libs`
endif

# BOOST INTERVAL SUPPORT
# MPFR and GMP have to be linked
MPFR :=
MPFRINCS :=
MPFRLIBS :=
GMP :=
GMPINCS :=
GMPLIBS :=

#includes
HOMEDIR := ..
INCS := -I$(CHOMP)/include
ifeq ($(HAVE_SUCCINCT),yes)
INCS += -I$(SDSL)/include
endif
ifeq ($(USE_CAPD),yes)
INCS += -I$(CAPD)/include
INCS += $(CAPDINCS)
endif
INCS += -I$(CLUSTER)/include
INCS += -I$(BOOST)/include
INCS += -I$(GRAPHICS)/include
INCS += -I./include/
INCS += -I$(MODELDIR)
INCS += -I/usr/include/python2.7
#libraries
LINKFLAGS := -L$(CHOMP)/lib
LINKFLAGS += -L$(BOOST)/lib
LINKFLAGS += -L$(GRAPHICS)/lib
LINKFLAGS += -L$(CAPD)/lib

LINKLIBS := -lboost_serialization -lboost_thread -lboost_system -lboost_chrono
LINKLIBS += -lpython2.7 -lboost_python
LINKLIBS += -lX11
LINKLIBS += -lmpfr
LINKLIBS += -lgmp

ifeq ($(USE_CAPD),yes)
LINKFLAGS += -L$(CAPD)/lib
LINKLIBS += $(CAPDLIBS)
endif

ifeq ($(HAVE_SUCCINCT),yes)
CXXFLAGS += -DNDEBUG -mSSE4.2
LINKFLAGS += -L$(SDSL)/lib
LINKLIBS += -lsdsl -ldivsufsort -ldivsufsort64
endif

ifeq ($(USE_BOOST_INTERVAL),yes)
LINKLIBS += -lgmp -lmpfr
endif 

# directory to store build products
OBJDIR := ./build
SRCDIR := ./source

# Variables "make" uses for implicit rules
CC := mpicxx
CXX := mpicxx
#mpicxx
CXXFLAGS := -O3 -Wall -ftemplate-depth=1024 -ggdb $(INCS)
LDFLAGS := $(LINKFLAGS)
LDLIBS := $(LINKLIBS)
