#!/bin/bash

mkdir graphs || exit 1
cd graphs || exit 1
../makeDatabaseZooSQL/main $1/database.mdb $1 `basename $1`.txt || exit 1
cd .. || exit 1

rm -rf $1/Zoo || exit 1
cp -rf template $1/Zoo || exit 1
mv -f graphs $1/Zoo || exit 1
$1/Zoo/COMPUTE $1 || exit 1


# copy the webpage with SQL query 
# create the html file
cd MakeWebpage
cd QueryDatabase/template
./createWebpage.sh "$1" "Zoo"
cd ../..
cp QueryDatabase/template/indexSQL.html "$1/Zoo"
cp QueryDatabase/template/checkradio-form.php "$1/Zoo"
cd ..


cd $1/Zoo

