#ifndef COLORMAP_H
#define COLORMAP_H

// temporary solution

std::string colorHex ( uint64_t & index ) {

  // This is generated by a python script.
  // Based on the qualitative colormap Paired
  // 9 colors
  std::string colors[] = { "#a6cee3", "#579fa4", "#51af42", "#f88887", "#f17047", "#ff850b", "#af91c5", "#cdbe99", "#b15928" };

  // 19 colors
  // std::string colors[] = { "#a6cee3", "#549ac7", "#3e8dab", "#96cc92", "#7dc563", "#40a033", "#b89c75", "#f57777", "#e62a2c", "#f17047", "#fdb761", "#fe901e", "#ed9047", "#cdafc9", "#926eb3", "#86629a", "#e0d799", "#e0bd6c", "#b15928" };

  if ( index > sizeof(colors)/sizeof(*colors) ) {
    std::cout << "Not enough colors.\n";
    abort();
  }

  return colors[index];
}



#endif
