#ifndef COLORMAP_H
#define COLORMAP_H

// temporary solution

std::string colorHex ( uint64_t & index ) {

  // This is generated by a python script.
  // Based on the qualitative colormap Paired
  // 9 colors
  // std::string colors[] = { "#a6cee3", "#579fa4", "#51af42", "#f88887", "#f17047", "#ff850b", "#af91c5", "#cdbe99", "#b15928" };

  // 19 colors
  // Paired
  // std::string colors[] = { "#a6cee3", "#549ac7", "#3e8dab", "#96cc92", "#7dc563", "#40a033", "#b89c75", "#f57777", "#e62a2c", "#f17047", "#fdb761", "#fe901e", "#ed9047", "#cdafc9", "#926eb3", "#86629a", "#e0d799", "#e0bd6c", "#b15928" };

  // Customized
  std::string colors[] = { "#ffffff", // white
                           "#999999", // gray
                           "#a6cee3", // blue shade 1
                           "#549ac7", // blue shade 2
                           "#3333ff", // blue shade 3
                           "#96cc92", // green shade 1
                           "#00cc33", // green shade 2
                           "#40a033", // green shade 3
                           "#ff66cc", //
                           "#f57777",
                           "#e62a2c",
                           "#ffff33", //
                           "#ffcc00", //
                           "#ff9900",
                          //  "#ed9047",
                           "#cdafc9",
                          //  "#926eb3",
                          //  "#86629a",
                           "#9933cc",
                           "#e0d799",
                           "#e0bd6c",
                           "#b15928" };

  // Set1
  // std::string colors[] = { "#e41a1c", "#984661", "#4c72a5", "#3e8e95", "#48a365", "#5e995e", "#7f6e85", "#a35392", "#d0694a", "#ff8101", "#ffb917", "#fff12e", "#e1c72f", "#ba7c2b", "#ba604d", "#dd738f", "#ec84ba", "#c28eaa", "#999999" };

  if ( index > sizeof(colors)/sizeof(*colors) ) {
    std::cout << "Not enough colors.\n";
    abort();
  }

  return colors[index];
}



#endif
